// rootRouter.js
const express = require("express");
const userRoutes = require("./modules/user/route");
const incomeRoutes = require("./modules/income/route");
const expenseRoutes = require("./modules/expense/route");
const driverIncome = require("./modules/driver.income/route");
const inventoryRoutes = require("./modules/inventory/route");
const vehicleProfileRoutes = require("./modules/vehicel.profile/route");
const vehicleRoutes = require("./modules/vehicle.document/route");
const tripRouter = require("./modules/trip.booking/route");
const clientRouer = require("./modules/client/route");
const inqiueryRouter = require("./modules/inquiry/route");
const maintenanceRouter = require("./modules/maintananceTwo/Route/MaintenanceRoute");
const repairRouter = require("./modules/maintananceTwo/Route/RepairRoute");
const breakdownRoute = require("./modules/maintananceTwo/Route/BreakdownRoute");
const notificationRoute = require("./modules/maintananceTwo/Route/NotificationRoute");
const router = express.Router();

router.use("/users", userRoutes);
router.use("/incomes", incomeRoutes);
router.use("/expenses", expenseRoutes);
router.use("/driver-income", driverIncome);
router.use("/inventory", inventoryRoutes);
router.use("/vprofiles", vehicleProfileRoutes);
router.use("/vehicles", vehicleRoutes);
router.use("/trips", tripRouter);
router.use("/booking-users", clientRouer);
router.use("/inquiries", inqiueryRouter);
router.use("/maintenance", maintenanceRouter);
router.use("/repair", repairRouter);
router.use("/breakdown", breakdownRoute);
router.use("/notification", notificationRoute);
module.exports = router;
